<?php

/**
 * @file
 * Primary module hooks for Drupal Atomic Builder module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function dab_theme($existing, $type, $theme, $path) {
  return [
    'dab_renderer' => [
      'variables' => [
        'component_path' => NULL,
        'iframe_src' => '',
        'reset_button' => NULL,
        'reload_button' => NULL,
        'responsive_select' => NULL,
        'template_select' => NULL,
        'version_select' => NULL,
      ],
    ],
    'dab_component_list' => [
      'variables' => [
        'components_types' => [],
        'components' => [],
        'form' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_toolbar_alter().
 */
function dab_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'dab/toolbar';
}
